development:
  adapter: postgresql
  database: lamington_properties_dev
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: lamington_properties_test
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  
production:
  adapter: postgresql
  database: lamington_properties_production
  host: localhost
  username: Doug
  password: ENV['DEV_PASSWORD']
  pool: 5
  timeout: 5000